key: sk-123456 # 自定义一个
agent_id: naQivTmsDa # 在Header的X-AgentID里，如果你看到的X-AgentID是两段，即中间有「/」的，前面那段才是agent_id
hy_user: IcOzg8ZfoW57XBmP # 在Cookie里
hy_token: zzx8aUbyCSrkBioR7l3KEZ93nJPBNX8DyETDJaD8OmEOO8hDlYnJXXEuWMSGuo2b # 在Cookie里
port: 7555 # 监听端口，若没有冲突可以不修改
